{
  accounts: [
    {
      account_id: 'wn7k6pWVWeclxBR1A8WBFyWaJqZlgXurmrkzL',
      balances: {
        available: 100,
        current: 110,
        iso_currency_code: 'USD',
        limit: null,
        unofficial_currency_code: null
      },
      mask: '0000',
      name: 'Plaid Checking',
      official_name: 'Plaid Gold Standard 0% Interest Checking',
      subtype: 'checking',
      type: 'depository'
    },
    {
      account_id: '5KQAXNvEv1T8JQVnpjaQIWyjDNV5GxfZ8ZRXb',
      balances: {
        available: 200,
        current: 210,
        iso_currency_code: 'USD',
        limit: null,
        unofficial_currency_code: null
      },
      mask: '1111',
      name: 'Plaid Saving',
      official_name: 'Plaid Silver Standard 0.1% Interest Saving',
      subtype: 'savings',
      type: 'depository'
    },
    {
      account_id: 'JgrjyzMeMKc38W6rqaVWTqNQJM91pxTdkdaXn',
      balances: {
        available: null,
        current: 1000,
        iso_currency_code: 'USD',
        limit: null,
        unofficial_currency_code: null
      },
      mask: '2222',
      name: 'Plaid CD',
      official_name: 'Plaid Bronze Standard 0.2% Interest CD',
      subtype: 'cd',
      type: 'depository'
    },
    {
      account_id: 'kZKNRa757ruXGRmxgjrRSLz3aylVExiWoWN7a',
      balances: {
        available: null,
        current: 410,
        iso_currency_code: 'USD',
        limit: 2000,
        unofficial_currency_code: null
      },
      mask: '3333',
      name: 'Plaid Credit Card',
      official_name: 'Plaid Diamond 12.5% APR Interest Credit Card',
      subtype: 'credit card',
      type: 'credit'
    },
    {
      account_id: 'lMrPR4eVezTWxyqdBZzySzjNdEVnMpiZRZjB6',
      balances: {
        available: 43200,
        current: 43200,
        iso_currency_code: 'USD',
        limit: null,
        unofficial_currency_code: null
      },
      mask: '4444',
      name: 'Plaid Money Market',
      official_name: 'Plaid Platinum Standard 1.85% Interest Money Market',
      subtype: 'money market',
      type: 'depository'
    },
    {
      account_id: 'qgdZ6eLVLac9XybJZlQyHvZ5MN1x6yCdRd9lX',
      balances: {
        available: null,
        current: 320.76,
        iso_currency_code: 'USD',
        limit: null,
        unofficial_currency_code: null
      },
      mask: '5555',
      name: 'Plaid IRA',
      official_name: null,
      subtype: 'ira',
      type: 'investment'
    },
    {
      account_id: 'K8z7LB1Q1rFxvmkzE9Pmul3EzMDBkvCV1VeoW',
      balances: {
        available: null,
        current: 23631.9805,
        iso_currency_code: 'USD',
        limit: null,
        unofficial_currency_code: null
      },
      mask: '6666',
      name: 'Plaid 401k',
      official_name: null,
      subtype: '401k',
      type: 'investment'
    },
    {
      account_id: 'r8aM6QpVp4FKy19jeWl1IWnXMaEozLfl1ljbr',
      balances: {
        available: null,
        current: 65262,
        iso_currency_code: 'USD',
        limit: null,
        unofficial_currency_code: null
      },
      mask: '7777',
      name: 'Plaid Student Loan',
      official_name: null,
      subtype: 'student',
      type: 'loan'
    },
    {
      account_id: 'zyZW68kqkEHEznDVqGRnSZxKmaAbjNCoQoRd4',
      balances: {
        available: null,
        current: 56302.06,
        iso_currency_code: 'USD',
        limit: null,
        unofficial_currency_code: null
      },
      mask: '8888',
      name: 'Plaid Mortgage',
      official_name: null,
      subtype: 'mortgage',
      type: 'loan'
    }
  ],
  item: {
    available_products: [
      'assets',
      'auth',
      'balance',
      'credit_details',
      'identity',
      'income',
      'liabilities'
    ],
    billed_products: [ 'investments', 'transactions' ],
    consent_expiration_time: null,
    error: null,
    institution_id: 'ins_3',
    item_id: 'axWqRAzVzLcnleNWmbyeSNG3GjpkGWFZeq4E8',
    webhook: ''
  },
  request_id: '4ipr6oYgxCMqCL3',
  total_transactions: 16,
  transactions: [
    {
      account_id: '5KQAXNvEv1T8JQVnpjaQIWyjDNV5GxfZ8ZRXb',
      account_owner: null,
      amount: 25,
      authorized_date: null,
      category: [ 'Payment', 'Credit Card' ],
      category_id: '16001000',
      date: '2020-12-11',
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null
      },
      merchant_name: null,
      name: 'CREDIT CARD 3333 PAYMENT *//',
      payment_channel: 'other',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'qgdZ6eLVLac9XybJZlQyHvZ1mm5ndvfdPoRM4',
      transaction_type: 'special',
      unofficial_currency_code: null
    },

    //////// ONE TRANSACTION////////
    // {
    //   account_id: 'wn7k6pWVWeclxBR1A8WBFyWaJqZlgXurmrkzL',
    //   account_owner: null,
    //   amount: 5.4,                         <---------------AMOUNT 4
    //   authorized_date: null,
    //   category: [ 'Travel', 'Taxi' ],      <---------------CATEGORY 2
    //   category_id: '22016000',
    //   date: '2020-12-11',                  <----------------DATE 3
    //   iso_currency_code: 'USD',
    //   location: {
    //     address: null,
    //     city: null,
    //     country: null,
    //     lat: null,
    //     lon: null,
    //     postal_code: null,
    //     region: null,
    //     store_number: null
    //   },
    //   merchant_name: 'Uber',
    //   name: 'Uber 063015 SF**POOL**',      <-----------------NAME 1
    //   payment_channel: 'in store',
    //   payment_meta: {
    //     by_order_of: null,
    //     payee: null,
    //     payer: null,
    //     payment_method: null,
    //     payment_processor: null,
    //     ppd_id: null,
    //     reason: null,
    //     reference_number: null
    //   },
    //   pending: false,
    //   pending_transaction_id: null,
    //   transaction_code: null,
    //   transaction_id: 'VReEzQbAb7CMwvae8zKvszALQQqeozuWyREdD',
    //   transaction_type: 'special',
    //   unofficial_currency_code: null
    // },
    {
      account_id: 'lMrPR4eVezTWxyqdBZzySzjNdEVnMpiZRZjB6',
      account_owner: null,
      amount: 5850,
      authorized_date: null,
      category: [ 'Transfer', 'Debit' ],
      category_id: '21006000',
      date: '2020-12-10',
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null
      },
      merchant_name: null,
      name: 'ACH Electronic CreditGUSTO PAY 123456',
      payment_channel: 'other',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: 'ACH',
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: '4qeWA4989gULGxWZjmMxSMrgeeXG9MudVkLLA',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: 'JgrjyzMeMKc38W6rqaVWTqNQJM91pxTdkdaXn',
      account_owner: null,
      amount: 1000,
      authorized_date: null,
      category: [ 'Transfer', 'Deposit' ],
      category_id: '21007000',
      date: '2020-12-10',
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null
      },
      merchant_name: null,
      name: 'CD DEPOSIT .INITIAL.',
      payment_channel: 'other',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'r8aM6QpVp4FKy19jeWl1IWnEjjXZ8Whl9o1MK',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: 'kZKNRa757ruXGRmxgjrRSLz3aylVExiWoWN7a',
      account_owner: null,
      amount: 78.5,
      authorized_date: null,
      category: [ 'Recreation', 'Gyms and Fitness Centers' ],
      category_id: '17018000',
      date: '2020-12-09',
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null
      },
      merchant_name: 'Touchstone',
      name: 'Touchstone Climbing',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'zyZW68kqkEHEznDVqGRnSZxAJJK7EZuoBqQQx',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: 'wn7k6pWVWeclxBR1A8WBFyWaJqZlgXurmrkzL',
      account_owner: null,
      amount: -500,
      authorized_date: null,
      category: [ 'Travel', 'Airlines and Aviation Services' ],
      category_id: '22001000',
      date: '2020-12-09',
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null
      },
      merchant_name: 'United Airlines',
      name: 'United Airlines',
      payment_channel: 'other',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'wn7k6pWVWeclxBR1A8WBFyWZ44az7yhrRLmVM',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: 'wn7k6pWVWeclxBR1A8WBFyWaJqZlgXurmrkzL',
      account_owner: null,
      amount: 12,
      authorized_date: null,
      category: [ 'Food and Drink', 'Restaurants', 'Fast Food' ],
      category_id: '13005032',
      date: '2020-12-08',
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: '3322'
      },
      merchant_name: "McDonald's",
      name: "McDonald's",
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: '5KQAXNvEv1T8JQVnpjaQIWyVooj1JWhZyg8dj',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: 'wn7k6pWVWeclxBR1A8WBFyWaJqZlgXurmrkzL',
      account_owner: null,
      amount: 4.33,
      authorized_date: null,
      category: [ 'Food and Drink', 'Restaurants', 'Coffee Shop' ],
      category_id: '13005043',
      date: '2020-12-08',
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null
      },
      merchant_name: 'Starbucks',
      name: 'Starbucks',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'JgrjyzMeMKc38W6rqaVWTqN9DDQPoqIdMZkJN',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: 'wn7k6pWVWeclxBR1A8WBFyWaJqZlgXurmrkzL',
      account_owner: null,
      amount: 89.4,
      authorized_date: null,
      category: [ 'Food and Drink', 'Restaurants' ],
      category_id: '13005000',
      date: '2020-12-07',
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null
      },
      merchant_name: 'Sparkfun',
      name: 'SparkFun',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'kZKNRa757ruXGRmxgjrRSLzlee3NKLCWDwopg',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: '5KQAXNvEv1T8JQVnpjaQIWyjDNV5GxfZ8ZRXb',
      account_owner: null,
      amount: -4.22,
      authorized_date: null,
      category: [ 'Transfer', 'Credit' ],
      category_id: '21005000',
      date: '2020-12-06',
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null
      },
      merchant_name: null,
      name: 'INTRST PYMNT',
      payment_channel: 'other',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'K8z7LB1Q1rFxvmkzE9Pmul3D11EQbliVkn1Nd',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: 'kZKNRa757ruXGRmxgjrRSLz3aylVExiWoWN7a',
      account_owner: null,
      amount: 500,
      authorized_date: null,
      category: [ 'Travel', 'Airlines and Aviation Services' ],
      category_id: '22001000',
      date: '2020-11-26',
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null
      },
      merchant_name: 'United Airlines',
      name: 'United Airlines',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'BenBo84x4gSGAKZMBXlKUa3NPPgl6aTw5Zggd',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: 'wn7k6pWVWeclxBR1A8WBFyWaJqZlgXurmrkzL',
      account_owner: null,
      amount: 6.33,
      authorized_date: null,
      category: [ 'Travel', 'Taxi' ],
      category_id: '22016000',
      date: '2020-11-24',
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null
      },
      merchant_name: 'Uber',
      name: 'Uber 072515 SF**POOL**',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'lMrPR4eVezTWxyqdBZzySzjVvvN86zuZgJR7K',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: 'kZKNRa757ruXGRmxgjrRSLz3aylVExiWoWN7a',
      account_owner: null,
      amount: 500,
      authorized_date: null,
      category: [ 'Food and Drink', 'Restaurants' ],
      category_id: '13005000',
      date: '2020-11-21',
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null
      },
      merchant_name: 'Tectra Inc',
      name: 'Tectra Inc',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: '3l7EZaygyDioGmEXBpymSnxw55kgGntqbPEEz',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: 'kZKNRa757ruXGRmxgjrRSLz3aylVExiWoWN7a',
      account_owner: null,
      amount: 2078.5,
      authorized_date: null,
      category: [ 'Payment' ],
      category_id: '16000000',
      date: '2020-11-20',
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null
      },
      merchant_name: null,
      name: 'AUTOMATIC PAYMENT - THANK',
      payment_channel: 'other',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'axWqRAzVzLcnleNWmbyeSNGBzzkmxNF7JPDDL',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: 'kZKNRa757ruXGRmxgjrRSLz3aylVExiWoWN7a',
      account_owner: null,
      amount: 500,
      authorized_date: null,
      category: [ 'Food and Drink', 'Restaurants', 'Fast Food' ],
      category_id: '13005032',
      date: '2020-11-20',
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null
      },
      merchant_name: 'KFC',
      name: 'KFC',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'd4nzRKxVxAfyE86njLD8hgAjLLB14gtZzGRRx',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: 'kZKNRa757ruXGRmxgjrRSLz3aylVExiWoWN7a',
      account_owner: null,
      amount: 500,
      authorized_date: null,
      category: [ 'Shops', 'Sporting Goods' ],
      category_id: '19046000',
      date: '2020-11-20',
      iso_currency_code: 'USD',
      location: {
        address: null,
        city: null,
        country: null,
        lat: null,
        lon: null,
        postal_code: null,
        region: null,
        store_number: null
      },
      merchant_name: 'Madison Bicycle Shop',
      name: 'Madison Bicycle Shop',
      payment_channel: 'in store',
      payment_meta: {
        by_order_of: null,
        payee: null,
        payer: null,
        payment_method: null,
        payment_processor: null,
        ppd_id: null,
        reason: null,
        reference_number: null
      },
      pending: false,
      pending_transaction_id: null,
      transaction_code: null,
      transaction_id: 'xbe86oAVAZF6xjqJwk3jCXBewwZqkXtnPNeeq',
      transaction_type: 'place',
      unofficial_currency_code: null
    }
  ],
  status_code: 200
}